### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by rugk** [flathub/im.dino.Dino#1]
How can I install the beta version of this app to be able to use it? :thinking:

**Comment by Newbytee** [comment]
You need Flathub Beta. See https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by rugk** [comment]
Oh thanks! I can confirm it works well like this:
```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta im.dino.Dino 
```

:upside_down_face:

**Comment by Newbytee** [comment]
What's with the upside down face?

**Comment by rugk** [comment]
Uhm no relevance. It works and I guess I can close this issue.😅😅
