### ISSUE TITLE
"Could not connect: No such file or directory" on launch

### ISSUE THREAD

**Issue by Newbytee** [flathub/im.dino.Dino#2]
Hi! I'm trying to run this, but when I open it, i just get the message "Could not connect: No such file or directory" printed to the terminal. No other error appears. Do you have any ideas regarding what this might be about?

**Comment by Newbytee** [comment]
Hm, today it is working somehow. Not sure what changed. I still get the same error if I launch Dino from a terminal, but the window appears anyway.

**Comment by Aman9das** [comment]
Closing as apparently resolved... I hope that's alright?
