### ISSUE TITLE
Crash on video call

### ISSUE THREAD

**Issue by sonnyp** [flathub/im.dino.Dino#7]
Didn't investigate yet - more of a reminder.

When video calling a contact - Dino crashes shortly after the connection is established.
Cannot reproduce with audio call.
Cannot reproduce with non-flatpak Dino.

**Comment by sonnyp** [comment]
Update: cannot reproduce with org.gnome.Platform master

We might as well wait for GNOME 44

**Comment by sonnyp** [comment]
just to be clear, the dri permission is already given by `--device=all`

**Comment by Gert-dev** [comment]
Wow, that's strange - perhaps it was just a coincidence since it's somewhat unstable.

(By the way, I was also confused because the commit message mentions "Fix camera crash", but if `--device=all` implies `-device=dri`, how can this commit fix anything? :smile: )

**Comment by sonnyp** [comment]
Yep my bad - I'm used to PR title being used as commit title and forgot to amend the commit https://github.com/flathub/im.dino.Dino/pull/9

**Comment by sonnyp** [comment]
I'll close this - crash is solved.

**Comment by Aman9das** [comment]
Is this fixed in the latest release?
