### ISSUE TITLE
dino 0.4 crashes on reply or reactions

### ISSUE THREAD

**Issue by pravi** [flathub/im.dino.Dino#8]
On pureos byzantium (librem 5), dino crashes when trying to reply or add a reaction.

**Comment by sonnyp** [comment]
Dino flathub?

I can't reproduce on x86_64 or aarch64 (op6)  
Try updating `flatpak update org.gnome.Platform`

**Comment by pravi** [comment]
After flashing mobian bookworm, reply is working. I can't test on byzantium right now.
